---
title: "STAA 566 Maps"
author: "Sherry Schulz"
date: "3/3/2022"
output: html_document
knit: (function(input_file, encoding){out_dir<-'docs';rmarkdown::render(input_file,encoding=encoding,output_file=file.path(dirname(input_file),out_dir, 'index.html'))})
---
```{r setup, include=FALSE}
#Retain this code chunk!!!
library(knitr)
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

```{r}
install.packages("leaflet")
install.packages("leafpop")
install.packages("tidyr")
```

```{r}
library("leaflet")
library("tidyverse")
library("dplyr")
library("leafpop")
library("tidyr")
```

```{r}
life<-read.csv("Human_life_Expectancy.csv")
location<-read.csv("World_Locator.csv")
location<-location[,2:4] #Keeping columns 2, 3, and 4 of the location file and replace the file.
```


```{r}
life<-life[life$Level=="National",]
combined<-left_join(life, location, by = "Country") #For each row of national it is trying to match the location in the location file. Now it combines the 2 files.

```

```{r}
combined<-replace(combined, combined == "Not Available", NA) #replace Not Available to NA
for (i in 5:ncol(combined)){
  combined[,i] <- as.numeric(combined[,i])
} #loop from i=5 onward in combined, take the ith row in combined and replace it with numeric category.
```


```{r}
labs <- lapply(seq(nrow(X2019)), 
               function(i) {
  paste0( "", "Annual average: ",as.character(round(pm[i, "pm"],1)), '<br>', 
          ifelse(is.na(as.character(pm[i, "name"])),"",paste0(as.character(pm[i, "name"]), '<br>')), 
          as.character(pm[i, "city"]), ', ',
          as.character(pm[i, "statename"]),'' ) 
})

```



```{r}
combined %>%
  leaflet() %>%
  setView(lng=0, lat=0, zoom = 4) %>%
  addTiles() %>%
  addMarkers(lat=~latitude, lng=~longitude,
             icon=list(
               iconUrl="https://img.icons8.com/material/24/000000/arms-up.png",
               iconSize=c(30,30)
             ), label=~as.character(countrydat$X2019))
```

